### ISSUE TITLE
如何开启socks5代理呢

### ISSUE THREAD

**Issue by handbye** [editso/fuso#15]
![image](https://user-images.githubusercontent.com/26617058/145748334-330d8cad-9761-4374-bd04-2f7984f6152e.png)

**Comment by editso** [comment]
> ![image](https://user-images.githubusercontent.com/26617058/145748334-330d8cad-9761-4374-bd04-2f7984f6152e.png)

从 [v1.0.4-beta.2](https://github.com/editso/fuso/releases/tag/v1.0.4-beta.2) 以后不需要指定转发类型,内部自动判定类型

![9A) KY(DJ)DZ`I`B{3 IP](https://user-images.githubusercontent.com/37452715/145748919-060b951e-66a7-4b5d-96e2-d3aac8d61ea3.png)
