### ISSUE TITLE
-h 参数 无效，本地已重新修改

### ISSUE THREAD

**Issue by N0ooooone** [editso/fuso#2]
![Xnip2021-12-01_15-24-24](https://user-images.githubusercontent.com/22231287/144189883-3677463e-2296-4ee1-a7b8-8a5f92302e80.jpg)

**Comment by editso** [comment]
-t 参数指定为**socks**代理后 -h 参数就无效了

**Comment by editso** [comment]
> ![Xnip2021-12-01_15-24-24](https://user-images.githubusercontent.com/22231287/144189883-3677463e-2296-4ee1-a7b8-8a5f92302e80.jpg)
-t 参数指定为socks代理后 -h 参数就无效了
