### ISSUE TITLE
在进行桥接模式时，爆如下错误

### ISSUE THREAD

**Issue by PANDA-MS** [editso/fuso#23]
![image](https://user-images.githubusercontent.com/54650671/154994920-97daad64-20db-43ed-bcd2-d4caa49456d9.png)
192.168.140.129是fuc的地址

**Comment by editso** [comment]
> ![image](https://user-images.githubusercontent.com/54650671/154994920-97daad64-20db-43ed-bcd2-d4caa49456d9.png)
> 
> 192.168.140.129是fuc的地址

你 **-b33891** 指定的端口在服务端已经被占用了
