### ISSUE TITLE
Win2003 x86 无法使用

### ISSUE THREAD

**Issue by TryA9ain** [editso/fuso#27]
### Win2003 x86 无法使用
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/51145610/164154298-923f3b53-8709-40b9-b936-be1bd5059c43.png">

<img width="648" alt="image" src="https://user-images.githubusercontent.com/51145610/164154258-9444ff0c-bdf0-4245-9ac7-f3060cc61c02.png">

`systeminfo`

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/51145610/164154070-c0cc9c01-0a97-4a20-ae92-03641b6cc260.png">

`fuc.exe -h`

<img width="841" alt="image" src="https://user-images.githubusercontent.com/51145610/164154092-cdcc9233-3b9c-4f44-bddb-3e556dbbda87.png">

**Comment by editso** [comment]
可能是兼容问题，等我修复

**Comment by editso** [comment]
> ### Win2003 x86 无法使用
> <img alt="image" width="1197" src="https://user-images.githubusercontent.com/51145610/164154298-923f3b53-8709-40b9-b936-be1bd5059c43.png">
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/51145610/164154258-9444ff0c-bdf0-4245-9ac7-f3060cc61c02.png">
> 
> `systeminfo`
> 
> <img alt="image" width="1075" src="https://user-images.githubusercontent.com/51145610/164154070-c0cc9c01-0a97-4a20-ae92-03641b6cc260.png">
> 
> `fuc.exe -h`
> 
> <img alt="image" width="841" src="https://user-images.githubusercontent.com/51145610/164154092-cdcc9233-3b9c-4f44-bddb-3e556dbbda87.png">

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/37452715/164509366-3f3cd097-c509-4a9a-9dcf-1ce2937fd873.png">


> ### Win2003 x86 无法使用
> <img alt="image" width="1197" src="https://user-images.githubusercontent.com/51145610/164154298-923f3b53-8709-40b9-b936-be1bd5059c43.png">
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/51145610/164154258-9444ff0c-bdf0-4245-9ac7-f3060cc61c02.png">
> 
> `systeminfo`
> 
> <img alt="image" width="1075" src="https://user-images.githubusercontent.com/51145610/164154070-c0cc9c01-0a97-4a20-ae92-03641b6cc260.png">
> 
> `fuc.exe -h`
> 
> <img alt="image" width="841" src="https://user-images.githubusercontent.com/51145610/164154092-cdcc9233-3b9c-4f44-bddb-3e556dbbda87.png">

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/37452715/164509480-a6312c4b-bb5b-4abf-a3c3-ddc58c904dd4.png">


> ### Win2003 x86 无法使用
> <img alt="image" width="1197" src="https://user-images.githubusercontent.com/51145610/164154298-923f3b53-8709-40b9-b936-be1bd5059c43.png">
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/51145610/164154258-9444ff0c-bdf0-4245-9ac7-f3060cc61c02.png">
> 
> `systeminfo`
> 
> <img alt="image" width="1075" src="https://user-images.githubusercontent.com/51145610/164154070-c0cc9c01-0a97-4a20-ae92-03641b6cc260.png">
> 
> `fuc.exe -h`
> 
> <img alt="image" width="841" src="https://user-images.githubusercontent.com/51145610/164154092-cdcc9233-3b9c-4f44-bddb-3e556dbbda87.png">

排查到兼容问题修复后会缺少动态库**bcrypt.dll**，这个问题可能是第三方加密库依赖导致的，所以你需要对流量进行加密吗
<img width="969" alt="image" src="https://user-images.githubusercontent.com/37452715/164509800-23c2b4f5-1634-482d-a4f3-7c5844a1af40.png">

**Comment by editso** [comment]
我上传了一份兼容的版本， 但是你需要自己修复**bcrypt.dll**
补丁程序：[CryptGenRandom](https://en.wikipedia.org/wiki/CryptGenRandom)
Fuso: [fuso-win2003.zip](https://github.com/editso/fuso/files/8533322/fuso-win2003.zip)
