### ISSUE TITLE
external IP forward

### ISSUE THREAD

**Issue by lootoos** [editso/fuso#33]
The fuso server will take the external IP of the connected player and transfer it to the fuso client so that the players have the correct IP on the Minecraft game server

The function will be useful for game servers\various sites

**Comment by editso** [comment]
> The fuso server will take the external IP of the connected player and transfer it to the fuso client so that the players have the correct IP on the Minecraft game server
> 
> The function will be useful for game servers\various sites

Did you mean socks5?

**Comment by lootoos** [comment]
I'm talking about TCP/UDP

**Comment by editso** [comment]
> I'm talking about TCP/UDP

How to notify your game server after forwarding to fuso client?

**Comment by lootoos** [comment]
> > I'm talking about TCP/UDP
> 
> How to notify your game server after forwarding to fuso client?

minecraft server has proxy-protocol support.
proofs: https://pastebin.com/Vuram6hS 90 line - proxy-protocol: false

**Comment by editso** [comment]
> > > I'm talking about TCP/UDP
> > 
> > 
> > How to notify your game server after forwarding to fuso client?
> 
> minecraft server has proxy-protocol support proofs: https://pastebin.com/Vuram6hS 90 line - proxy-protocol: false

OK
