### ISSUE TITLE
will you add tcp-fast-open?

### ISSUE THREAD

**Issue by lootoos** [editso/fuso#36]
TCP Fast Open (TFO), is an extension to the transmission control protocol (TCP) that helps reduce network [latency](https://www.keycdn.com/support/what-is-latency) by enabling data to be exchanged during the sender's initial TCP SYN. A traditional TCP handshake is a three step process that is carried out as follows.

The sender sends a SYN packet to the receiver to initiate the connection
The receiver sends a SYN-ACK packet back to the sender to let it know that it is ready to start transmitting data
The sender sends an ACK packet to the receiver
https://www.keycdn.com/support/tcp-fast-open

**Comment by editso** [comment]
> TCP Fast Open (TFO), is an extension to the transmission control protocol (TCP) that helps reduce network [latency](https://www.keycdn.com/support/what-is-latency) by enabling data to be exchanged during the sender's initial TCP SYN. A traditional TCP handshake is a three step process that is carried out as follows.
> 
> The sender sends a SYN packet to the receiver to initiate the connection The receiver sends a SYN-ACK packet back to the sender to let it know that it is ready to start transmitting data The sender sends an ACK packet to the receiver https://www.keycdn.com/support/tcp-fast-open

I am writing the code for the configuration file, thank you for your suggestion, I will add it to the configuration file
