### ISSUE TITLE
请问怎么做socks5的代理？

### ISSUE THREAD

**Issue by TryA9ain** [editso/fuso#4]
![image](https://user-images.githubusercontent.com/51145610/144744490-985387ee-b75b-4f51-ba39-69149c8f3974.png)

![image](https://user-images.githubusercontent.com/51145610/144744503-da30500e-6828-4910-9e7b-d1f6600e7b28.png)

服务端日志:

![image](https://user-images.githubusercontent.com/51145610/144744567-5d9b3224-8be1-4e75-8abf-585fe1e830ef.png)

**Comment by editso** [comment]
> ![image](https://user-images.githubusercontent.com/51145610/144744490-985387ee-b75b-4f51-ba39-69149c8f3974.png)
> 
> ![image](https://user-images.githubusercontent.com/51145610/144744503-da30500e-6828-4910-9e7b-d1f6600e7b28.png)
> 
> 服务端日志:
> 
> ![image](https://user-images.githubusercontent.com/51145610/144744567-5d9b3224-8be1-4e75-8abf-585fe1e830ef.png)

你连接服务端的端口貌似是错的

![`{6`6J~K3X_9NKADHRFZC@P](https://user-images.githubusercontent.com/37452715/144785705-88437af2-2ab3-4116-81cd-f016dbd8d1b4.png)
![A 6HO6J}WBF$Z)APMX{UOJ](https://user-images.githubusercontent.com/37452715/144785712-976e9066-0237-48b1-95d0-8057432ab3a2.png)

**Comment by editso** [comment]
抱歉 目前发现 **v1.0.4-beta** 无法使用 **socks5** 代理, 我已重新上传该版本, 请重新下载
