### ISSUE TITLE
流量加密模块用户可以自定义

### ISSUE THREAD

**Issue by daikerSec** [editso/fuso#5]
看了下加密模块，用的异或运算，虽然可以自定义异或的key，但是特征过于明显
![image](https://user-images.githubusercontent.com/26897699/144751300-cf930a5a-ab91-4a43-be20-1258420ffc7c.png)

是不是可以开放一个自定义加解密方式的API和文档。

**Comment by editso** [comment]
感谢你的建议, 文档还在整理中, 如果你急需要更换传输加密方式 你可以实现 **Cipher**, 该**Trait**可以实现自己的加密方式
