### ISSUE TITLE
无公网IP服务器通过转发所有流量到有公网IP服务器来访问公网

### ISSUE THREAD

**Issue by Yiniau** [editso/fuso#54]
具体表述：
有两台服务器，服务器A有公网IP，服务器B没有，
目前服务商（联通云）限制无公网IP的服务器的外网访问，
是否可以通过 fuso 内网穿透，转发服务器B的流量到A来解决这个问题，同时服务器A上也有一些服务在跑，不能影响现有服务
扩展一下，如果加了服务器C同样无公网IP要如何处理？
（目前服务器都需要格外购买NAT才能比较方便地处理这个情况，我们搞公益的想省钱...）

**Comment by editso** [comment]
> 具体表述：
> 
> 有两台服务器，服务器A有公网IP，服务器B没有，
> 
> 目前服务商（联通云）限制无公网IP的服务器的外网访问，
> 
> 是否可以通过 fuso 内网穿透，转发服务器B的流量到A来解决这个问题，同时服务器A上也有一些服务在跑，不能影响现有服务
> 
> 扩展一下，如果加了服务器C同样无公网IP要如何处理？
> 
> （目前服务器都需要格外购买NAT才能比较方便地处理这个情况，我们搞公益的想省钱...）

在你有公网ip的服务器上启动服务端(fus) 然后在你无公网ip的服务器中启动客户端(fuc) 并且你需要确保你的无公网ip服务器 能够正常和带公网ip服务器通信 否则无法使用 详细用法在项目主页说明中

**Comment by Yiniau** [comment]
sorry，没理解首页的文档
我在服务器A上启动了 fus，在服务器B中具体要如何设置参数？
我尝试了 fuc * -b * --forward-host <ip_of_a> --forward-port 6722
但是似乎不支持统配符，我的需求还是通过转发这个B上的所有请求到A，A再转发到公网来让B访问公网

**Comment by kechocy** [comment]
> sorry，没理解首页的文档 我在服务器A上启动了 fus，在服务器B中具体要如何设置参数？ 我尝试了 fuc * -b * --forward-host <ip_of_a> --forward-port 6722 但是似乎不支持统配符，我的需求还是通过转发这个B上的所有请求到A，A再转发到公网来让B访问公网

服务器A启动 fus
服务器B使用 ./fuc -b 6666 --forward-host 127.0.0.1 --forward-port 80 [ip_A]
然后可以通过 http://[ip_A]:6666 访问到位于服务器B上的 80 网站服务

**Comment by Yiniau** [comment]
用frp了，frp有现成的文档
