### ISSUE TITLE
支持域名前置的代理

### ISSUE THREAD

**Issue by daikerSec** [editso/fuso#6]
现在客户端跟服务端的通信用的是xor加密的tcp连接，李哥说将来打算支持kcp协议。

是否可以支持https或者wss通讯，并且host可以用户自定义，这样就可以使用cdn 进行域名前置了。隐藏真实服务端的ip。
![image](https://user-images.githubusercontent.com/26897699/144751652-3e987970-b0ed-407c-8ab1-08ac504dd221.png)
![image](https://user-images.githubusercontent.com/26897699/144751678-1623dc0e-4ab4-43c5-bfe4-2c1fb3a53afb.png)

frp可以实现，参考这个https://buaq.net/go-52132.html

**Comment by editso** [comment]
下一次功能更新将会支持
