### ISSUE TITLE
能否支持转发远程3389连接

### ISSUE THREAD

**Issue by ttsite** [editso/fuso#9]
不知道这款工具是否支持转发远程内网3389连接。如果支持请问格式是什么？

**Comment by editso** [comment]
> 不知道这款工具是否支持转发远程内网3389连接。如果支持请问格式是什么？

可以转发任意端口, 参考下面例子:
![NT4@V3GGZ0356(R7H6GNSK](https://user-images.githubusercontent.com/37452715/145335547-0e0f5981-a852-4ac4-9829-e6b9da32becd.png)

**Comment by ttsite** [comment]
好象不行。按您的格式测试了几台内网机器。都无法完整连接。提示 由于数据加密错误,这个会话将结束。请重新接到远程计算机。
![11](https://user-images.githubusercontent.com/43260559/145338056-106db53b-c43d-4e12-b443-1d0567ec3d85.png)

**Comment by editso** [comment]
> 好象不行。按您的格式测试了几台内网机器。都无法完整连接。提示 由于数据加密错误,这个会话将结束。请重新接到远程计算机。 ![11](https://user-images.githubusercontent.com/43260559/145338056-106db53b-c43d-4e12-b443-1d0567ec3d85.png)

麻烦提供下你下载的版本, 我这边是win10测试是通过的

**Comment by ttsite** [comment]
![信息](https://user-images.githubusercontent.com/43260559/145377058-83be9560-d6ef-446e-bb30-733e1938f440.png)

**Comment by editso** [comment]
> ![信息](https://user-images.githubusercontent.com/43260559/145377058-83be9560-d6ef-446e-bb30-733e1938f440.png) v1.0.4-beta

我已经上传了最新编译的包 [v1.0.4-alpha](https://github.com/editso/fuso/releases/tag/v1.0.4-alpha)

**Comment by ttsite** [comment]
我在试下稍晚给您反馈,谢谢!

**Comment by ttsite** [comment]
测试还是我最初发图的例子。测试系统win2008 win2007 win2019 win2016都是这样

**Comment by editso** [comment]
> 测试还是我最初发图的例子。测试系统win2008 win7 win2019 win2016 win2012都是这样

抱歉, 目前我还没找到具体问题所在, 因为我一直用的win10做的测试, 可否将你的联系方式发送到我的邮箱 admin@editso.com

**Comment by editso** [comment]
> 测试还是我最初发图的例子。测试系统win2008 win7 win2019 win2016 win2012都是这样

我刚刚已找到可能导致该问题的bug,  已上传修复后的包 [v1.0.4-beta.2](https://github.com/editso/fuso/releases/tag/v1.0.4-beta.2)

**Comment by ttsite** [comment]
> > 测试系统还是我最初发图的例子。 测试系统win2008 win7 win2019 win2016 win2012都是这样
> 
> 我刚刚找到可能导致该问题的代码，已上传修复后的包[v1.0.4-beta.2](https://github.com/editso/fuso/releases/tag/v1.0.4-beta.2)

刚虚拟机测试了一下是可以的。明日我在特理机测试下给您回复。心苦了。多谢

**Comment by editso** [comment]
> > > 测试系统还是我最初发图的例子。 测试系统win2008 win7 win2019 win2016 win2012都是这样
> > 
> > 
> > 我刚刚找到可能导致该问题的代码，已上传修复后的包[v1.0.4-beta.2](https://github.com/editso/fuso/releases/tag/v1.0.4-beta.2)
> 
> 刚虚拟机测试了一下是可以的。明日我在特理机测试下给您回复。心苦了。多谢

测试通过了吗
